// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-kJVpflQTghCEODvOtDtkvppQuh9m8FY',
    appId: '1:774834550320:web:f989ffe39e232cf7ea9ff5',
    messagingSenderId: '774834550320',
    projectId: 'flutterjeanpaulcc62b',
    authDomain: 'flutterjeanpaulcc62b.firebaseapp.com',
    storageBucket: 'flutterjeanpaulcc62b.firebasestorage.app',
    measurementId: 'G-6JC52ZB2Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoxVCyu1M3PmvyncE4i4yDDR7BW1zc2k',
    appId: '1:774834550320:android:e690153002116001ea9ff5',
    messagingSenderId: '774834550320',
    projectId: 'flutterjeanpaulcc62b',
    storageBucket: 'flutterjeanpaulcc62b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkhu8hZBq-oBYB-Od38HLGYvstIZfQnUg',
    appId: '1:774834550320:ios:97af5e05ab14fd0dea9ff5',
    messagingSenderId: '774834550320',
    projectId: 'flutterjeanpaulcc62b',
    storageBucket: 'flutterjeanpaulcc62b.firebasestorage.app',
    iosBundleId: 'com.example.watchlistManagerMoviesSeries',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkhu8hZBq-oBYB-Od38HLGYvstIZfQnUg',
    appId: '1:774834550320:ios:97af5e05ab14fd0dea9ff5',
    messagingSenderId: '774834550320',
    projectId: 'flutterjeanpaulcc62b',
    storageBucket: 'flutterjeanpaulcc62b.firebasestorage.app',
    iosBundleId: 'com.example.watchlistManagerMoviesSeries',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-kJVpflQTghCEODvOtDtkvppQuh9m8FY',
    appId: '1:774834550320:web:08e3ebcf5d522156ea9ff5',
    messagingSenderId: '774834550320',
    projectId: 'flutterjeanpaulcc62b',
    authDomain: 'flutterjeanpaulcc62b.firebaseapp.com',
    storageBucket: 'flutterjeanpaulcc62b.firebasestorage.app',
    measurementId: 'G-PH8R32RBGM',
  );
}
